# Generated by Django 4.2.4 on 2024-04-21 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_skill_profile_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='experience',
            field=models.TextField(default='Beginner', max_length=50),
        ),
    ]
