# Generated by Django 4.2.4 on 2024-04-22 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_openeddm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='openedDM',
        ),
    ]
